
export enum PaymentStatus {
  PAID = 'Paid',
  UNPAID = 'Unpaid',
  PARTIAL = 'Partial'
}

export enum ExpenseType {
  CREDIT = 'Credit', // Income/Collection
  DEBIT = 'Debit'    // Expense
}

// --- INVENTORY TYPES ---
export interface InventoryItem {
  id: string;
  name: string;
  type: string; // Changed to string to support custom types
  buyPrice: number;
  sellPrice: number;
  stockCount: number;
  
  // New Fields
  supplierName?: string;
  supplierAddress?: string;
  purchaseDate?: string; // NEW: Track when item was added/purchased

  // New Fields for Reporting
  initialStock?: number; // Stock count when first created
  totalBought: number;   // Cumulative count of items bought
  totalCost: number;     // Cumulative cost (Total Bought * Buy Price over time)
  
  description?: string;
}

export interface ClientAsset {
  id: string;
  inventoryItemId: string;
  name: string;
  assignedDate: string;
  status: 'Sold' | 'Lent' | 'Free'; // Sold = Client bought it, Lent = Returnable
  priceCharged: number; // If sold
}

// NEW: Inventory Log for Log Book
export interface InventoryTransaction {
  id: string;
  date: string;
  itemId: string;
  itemName: string;
  type: 'Purchase' | 'Restock' | 'StockOut' | 'Assign' | 'Return';
  quantity: number;
  clientId?: string;
  clientName?: string;
  remarks?: string;
}

export interface BandwidthPackage {
  id: string;
  name: string;
  bandwidth: string;
  price: number;
  remark?: string;
}

export interface Client {
  id: string;
  clientId: string; // The short display ID (e.g. 1001)
  username: string;
  name: string;
  contactNumber: string;
  fullAddress: string;
  area: string;
  clientType?: 'Home User' | 'Office' | 'Corporate' | 'Special' | 'Custom' | string; // NEW: Client Type
  lineType?: 'Fiber' | 'Cat5' | string; // NEW: Line Type
  bandwidthPackage?: string; // NEW: Bandwidth Package Name
  isActive: boolean;
  isArchived?: boolean; // NEW: For "Left Clients" (Permanently disconnected)
  leftDate?: string; // NEW: Date when client left
  baseMonthlyFee: number;
  joiningDate?: string; // NEW: Track when client joined
  customFields?: Record<string, string>; // For dynamic columns
  assignedAssets?: ClientAsset[]; // NEW: Track assets given to client
}

export interface MonthlyRecord {
  id: string; // Unique ID for this record
  clientId: string; // Link to Client UUID
  monthKey: string; // Format: "YYYY-MM"
  
  // Snapshot data (in case client details change later)
  displayClientId: string; // Snapshot of Client.clientId
  clientName: string;
  username: string;
  area: string;
  clientType?: string; // Snapshot
  lineType?: string; // Snapshot of line type
  bandwidthPackage?: string; // Snapshot of package
  contact: string;
  address: string;
  isActive: boolean; // Snapshot of active status

  // Billing
  billDate: string; // Date bill was generated
  payableAmount: number; // Monthly Fee + Previous Due
  paidAmount: number;
  paymentDate?: string;
  paymentMethod?: string;
  receiptNo?: string;
  status: PaymentStatus;
  
  // Overdue logic
  overdueMonths: number; // 0, 1, 2, 3
  remarks?: string;
  
  customFields?: Record<string, string>; // Snapshot of custom fields
}

export interface ExpenseTransaction {
  id: string;
  date: string;
  description: string;
  category?: string; // NEW: Expense Category
  amount: number;
  type: ExpenseType;
  relatedRecordId?: string; // If auto-generated from a client payment
}

export type ThemeColor = 'blue' | 'purple' | 'emerald' | 'rose' | 'orange';

export interface AppSettings {
  companyName: string;
  companyTagline?: string; // NEW
  companyAddress?: string; // NEW
  userName?: string; // NEW: For "Generated by..."
  currencySymbol: string;
  theme: 'light' | 'dark' | 'system';
  brandColor: ThemeColor; // NEW: Custom Brand Color
  customHeaders: Record<string, string>; // key: label
  columnOrder: string[]; // Order of columns in Master Sheet
  dynamicFields: string[]; // List of keys for custom created columns
  passwordHash: string; // Simple check
  
  // Security Question for Recovery
  securityQuestion?: string;
  securityAnswerHash?: string;

  // Backup & Updates
  autoBackupEnabled: boolean; // Controls Local Backup
  localBackupEnabled: boolean; // New: Distinct toggle for local disk
  cloudBackupEnabled: boolean; // New: Distinct toggle for cloud
  autoUpdateEnabled: boolean; // New: Toggle for app auto-updates
  
  lastBackupDate: string; // NEW: Track last backup (YYYY-MM-DD)
  maxDueDate?: number; // NEW: Day of month (e.g., 10) to consider "On Time"
  
  // Cloud Sync
  googleCloudConnected?: boolean;
  lastCloudSync?: string; // ISO String

  // Configuration
  bandwidthPackages: BandwidthPackage[]; // UPDATED: List of package objects
}

// --- NETWORK DIAGRAM TYPES ---
export interface DiagramNode {
    id: string;
    x: number;
    y: number;
    label: string;
    type: 'OLT' | 'Splitter' | 'Switch' | 'Router' | 'Client' | 'Server' | 'Cloud';
    color: string;
    assignedInventoryId?: string; 
    assignedInventoryName?: string;
    assignedDate?: string;
}

export interface DiagramLink {
    id: string;
    from: string;
    to: string;
    color: string;
    label?: string; // e.g., "Port 1" or Name
    length?: string; // e.g. "500m"
}

export interface NetworkDiagramState {
    nodes: DiagramNode[];
    links: DiagramLink[];
    zoom: number;
    pan: { x: number, y: number };
    rotation: number; // NEW: 0 to 360
}

export interface GlobalState {
  clients: Client[];
  records: MonthlyRecord[];
  expenses: ExpenseTransaction[];
  inventory: InventoryItem[]; 
  inventoryHistory: InventoryTransaction[]; // NEW: Comprehensive Log Book
  settings: AppSettings;
  currentViewMonth: string; // "YYYY-MM"
  networkDiagram?: NetworkDiagramState; // NEW: Persistent Diagram
}

// UI Types
export type ToastType = 'success' | 'error' | 'info' | 'warning';

export interface ToastMessage {
  id: string;
  type: ToastType;
  message: string;
}